/* Generated by Together */

package edu.swri.swiftvis.filters;

/**
* An interesting challenge would be to try to put this in the selection filter.
* the problem is that it is fundamentally O(n^2) and n only has to be inside the
* same timestep but making the function filter know that will be virtually
* impossible.
*
* Requested by Luke.
**/
public class ResonanceFilter {
}
