/* Generated by Together */

package edu.swri.swiftvis;

public interface DataSink extends GraphElement {
    boolean validInput(DataSource ds);
    void addInput(DataSource input);
    void removeInput(DataSource input);
    void moveUpInput(int index);
    int getNumSources();
    DataSource getSource(int which);
    void sourceAltered(DataSource source);
}
