/* Generated by Together */

package edu.swri.swiftvis.sources;

import javax.swing.*;

import edu.swri.swiftvis.GraphElement;

import java.io.File;
import java.util.List;

public class EncounterData extends AbstractSource {
    public EncounterData(JFrame mainFrame,File file) {
    }
    
    public EncounterData(EncounterData c,List<GraphElement> l) {
        super(c,l);
    }

    @Override
    public String getDescription(){ return "Encounter Data"; }

    public static String getTypeDescription(){ return "Encounter Data"; }

    @Override
    protected void setupSpecificPanelProperties() {
        JPanel panel=new JPanel();
        propPanel.add("Settings",panel);
    }

    /**
     * Tells you what a particular parameter is used for.
     */
    @Override
    public String getParameterDescription(int stream, int which){
        String[] desc={"Type","ID","Status"};
        return desc[which];
    }

    /**
     * Tells you what a particular value is used for.
     */
    @Override
    public String getValueDescription(int stream, int which){
        String[] desc={"Time","x","y","z","vx","vy","vz","mass"};
        return desc[which];
    }

    @Override
    public int getNumParameters(int stream){
        return 3;
    }

    @Override
    public int getNumValues(int stream){
        return 8;
    }

    @Override
    public EncounterData copy(List<GraphElement> l) {
        return new EncounterData(this,l);
    }
    
    @Override
    protected void redoAllElements() {
        // TODO
    }

    private static final long serialVersionUID=8823769832461l;
}
