package edu.swri.swiftvis;

import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.util.Hashtable;
import java.util.List;

import javax.swing.JComponent;

/* Generated by Together */

/**
 * This interface is the common supertype of everything that can be added into * the graph.  The main groups of subclasses are datasets, filters, and plots. *  * The program also has expectations for the constructors for a class.  You * need to look at the documentation of the different subtypes of this interface * to find what they expect. *  * If you want the program to automatically list some description for your element * when they set it up to allow that to be added, you should add a static method * String getTypeDescription().
 */

public interface GraphElement extends java.io.Serializable {

    String getDescription();

    Rectangle getBounds();

    void translate(int dx,int dy);

    void drawNode(Graphics2D g);

    JComponent getPropertiesPanel();
    
    GraphElement copy(List<GraphElement> l);
    
    void relink(Hashtable<GraphElement,GraphElement> linkHash);
    
    void redo();
    
    /**
     * This method does what the name implies, it clears out data vectors.
     * It is used for saving templates which shouldn't have the data in
     * them.
     */
    void clearData();
}
